question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Mythology",
        "type": "boolean",
        "difficulty": "easy",
        "question": "According to Greek Mythology, Zeus can control lightning.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Comics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Deadpool&#039;s identity is Slade Wilson.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Daft Punk originated in France.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Celebrities",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Marilyn Monroe was born on July 1, 1926.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Adolf Hitler was tried at the Nuremberg trials.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Linux was first created as an alternative to Windows XP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "An average human can go two weeks without water.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Activision created Battlefield 1.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A scalene triangle has two sides of equal length.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A plant that has a life cycle for more than a year is known as an annual.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are a total of 20 races in Formula One 2016 season.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are 2 player roles in Trouble in Terrorist Town.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Doki Doki Literature Club was developed in Japan.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
